app:
  name: api-rud
  port: "4000"
  http_server_idle_timeout: 60 #second
  encryption:
    salt: 10
    jwt_secret: Rahasia*1!

db:
  host: localhost
  port: 5432
  name: db_godock_mf
  user: postgres
  password: root
  connection_pool:
    max_idle_connection: 10
    max_open_connection: 30
    max_lifetime_connection: 60 #second
    max_idletime_connection: 60 #second
